<?php
 /* QeePHP Config File,Do not to modify this file! */ 
 return array (
  'DB_PASSWORD' => '123456',
  'DB_PREFIX' => 'windsforce_',
  'DB_NAME' => 'windsforce_v20141007',
  'DB_CACHE_FIELDS' => true,
  'DB_CACHE' => true,
  'DB_CACHE_TIME' => 86400000000,
  'APP_DEBUG' => false,
  'SHOW_RUN_TIME' => true,
  'SHOW_DB_TIMES' => true,
  'SHOW_GZIP_STATUS' => false,
  'RBAC_DATA_PREFIX' => 'rbac_',
  'COOKIE_PREFIX' => 'wf7da471_',
  'COOKIE_DOMAIN' => '',
  'QEEPHP_AUTH_KEY' => 'qeephpauthkey70F00C',
  'RBAC_ROLE_TABLE' => 'role',
  'RBAC_USERROLE_TABLE' => 'userrole',
  'RBAC_ACCESS_TABLE' => 'access',
  'RBAC_NODE_TABLE' => 'node',
  'USER_AUTH_ON' => true,
  'USER_AUTH_KEY' => 'authid5a0904',
  'ADMIN_USERID' => '1',
  'ADMIN_AUTH_KEY' => 'adminddFf1E',
  'USER_AUTH_MODEL' => 'user',
  'AUTH_PWD_ENCODER' => 'md5',
  'USER_AUTH_GATEWAY' => 'home://public/login',
  'NOT_AUTH_MODULE' => 'public,api,space,misc,wap,apps,search,index,homehelp,homesite',
  'REQUIRE_AUTH_MODULE' => '',
  'NOT_AUTH_ACTION' => '',
  'REQUIRE_AUTH_ACTION' => '',
  'GUEST_AUTH_ON' => true,
  'GUEST_AUTH_ID' => '-1',
  'RBAC_ERROR_PAGE' => 'home://public/rbacerror',
  'RBAC_GUEST_ACCESS' => 
  array (
    'home@stat@*' => true,
    'home@online@*' => true,
    'home@getpassword@*' => true,
    'home@userappeal@*' => true,
    'home@attachmentdownload@*' => true,
    'home@attachmentread@*' => true,
    'home@attachment@*' => true,
    'home@attachment@show' => false,
    'home@attachment@add' => false,
    'home@attachment@normal_upload' => false,
    'home@attachment@add_attachmentcomment' => false,
    'home@homesite@*' => true,
    'home@homehelp@*' => true,
    'home@announcement@*' => true,
    'group@ucenter@*' => true,
    'group@tag@*' => true,
    'group@group@joingroup' => true,
    'group@group@leavegroup' => true,
    'group@group@getcategory' => true,
    'group@grouptopic@set_grouptopicstyle' => true,
    'group@grouptopic@set_grouptopicside' => true,
    'group@create@*' => true,
  ),
  'RBAC_USER_ACCESS' => 
  array (
    'home@spaceadmin@*' => true,
    'home@spaceadmin@transfer' => false,
    'home@spaceadmin@dotransfer' => false,
    'home@pm@*' => true,
    'home@notice@*' => true,
    'home@friend@*' => true,
    'home@ucenter@index' => true,
    'home@ucenter@homefreshtopic' => true,
    'home@ucenter@audit_homefreshcomment' => true,
    'home@ucenter@feed' => true,
    'home@ucenter@tag' => true,
    'home@ucenter@tags' => true,
    'group@groupadmin@*' => true,
    'group@grouptopic@printtable' => true,
    'group@grouptopic@next' => true,
    'group@grouptopic@prev' => true,
    'group@grouptopic@readtopic' => true,
    'group@grouptopic@love' => true,
    'group@grouptopic@love_add' => true,
  ),
  'ERROR_PAGE' => 'home://public/page404',
  'TIME_ZONE' => 'Asia/Shanghai',
  'TEMPLATE_TAG_NOTE' => true,
  'CACHE_REPLACE_CHILDREN' => true,
  'APP_DEVELOP' => 0,
  'FRONT_TPL_DIR' => 'Default',
  'ADMIN_TPL_DIR' => 'Default',
  'CACHE_LIFE_TIME' => 8640000,
  'COOKIE_LANG_TEMPLATE_INCLUDE_APPNAME' => false,
  'FIREBUGFORIE' => false,
  'FRONT_LANGUAGE_DIR' => 'Zh-cn',
  'ADMIN_LANGUAGE_DIR' => 'Zh-cn',
  'LANG_SWITCH' => true,
  'LANG_ON' => false,
  'DEFAULT_APP' => 'group',
  'URL_MODEL' => 0,
  'URL_HTML_SUFFIX' => '.html',
  'URL_DOMAIN_ON' => false,
  'URL_DOMAIN' => '',
  'DOMAIN_ON' => false,
  'DOMAIN_TOP' => '',
  'DOMAIN_SUFFIX' => '',
  'START_ROUTER' => true,
  'U_PRO_VAR' => '',
  'CRON_ON' => true,
  'LOGINVIEW_IGNORE' => 
  array (
    0 => 'home@ucenter@view',
    1 => 'group@grouptopic@view',
  ),
  'APP_MENU' => 
  array (
  ),
  'RUNTIME_CACHE_BACKEND' => 'FileCache',
  'RUNTIME_CACHE_TIME' => 86400,
  'RUNTIME_CACHE_TIMES' => 
  array (
    'newuser' => 3600,
    'activeuser' => 3600,
    'hottag' => 3600,
    'hottagtop' => 3600,
    'site' => 3600,
  ),
  'RUNTIME_MEMCACHE_SERVERS' => 
  array (
  ),
  'RUNTIME_MEMCACHE_HOST' => '127.0.0.1',
  'RUNTIME_MEMCACHE_PORT' => 11211,
  'RUNTIME_MEMCACHE_COMPRESSED' => false,
  'RUNTIME_MEMCACHE_PERSISTENT' => true,
  'EDITOR_HEIGHT' => 1500,
  'GLOBALS_TAGS' => 
  array (
  ),
  'DB_HOST' => 'localhost',
  'DB_USER' => 'root',
)
?>