<?php
 /* QeePHP Config File,Do not to modify this file! */ 
 return array (
  'START_GZIP' => true,
  'APP_DEBUG' => false,
  'DB_HOST' => 'localhost',
  'DB_USER' => 'root',
  'DB_PASSWORD' => '123456',
  'DB_PREFIX' => 'windsforce_',
  'DB_CHAR' => 'utf8',
  'DB_NAME' => 'windsforce_v20141007',
  'DB_TYPE' => 'mysql',
  'DB_SCHEMA' => '',
  'DB_PORT' => 3306,
  'DB_CACHE' => true,
  'DB_META_CACHED' => true,
  'DB_DISTRIBUTED' => false,
  'DB_RW_SEPARATE' => false,
  'DB_DSN' => 'mysql://username:password@localhost:3306/dbname',
  'DB_PARAMS' => 
  array (
  ),
  'TEMPLATE_NOT_ALLOWS_FUNC' => 'echo,exit',
  'CACHE_LIFE_TIME' => 8640000,
  'CACHE_REPLACE_CHILDREN' => true,
  'THEME_SWITCH' => true,
  'TPL_DIR' => 'Default',
  'PHP_OFF' => true,
  'TEMPLATE_TAG_NOTE' => true,
  'TEMPLATE_SUFFIX' => '.html',
  'ERROR_PAGE' => 'home://public/page404',
  'SHOW_ERROR_MSG' => true,
  'TMPL_ACTION_ERROR' => 'message',
  'TMPL_ACTION_SUCCESS' => 'message',
  'TMPL_MODULE_ACTION_DEPR' => '_',
  'DEFAULT_AJAX_RETURN' => 'JSON',
  'TMPL_VAR_IDENTIFY' => 'array',
  'AUTO_ACCEPT_LANGUAGE' => true,
  'QEEPHP_AUTH_KEY' => 'qeephpauthkey70F00C',
  'RBAC_DATA_PREFIX' => 'rbac_',
  'TIME_ZONE' => 'Asia/Shanghai',
  'COOKIE_PREFIX' => 'wf7da471_',
  'COOKIE_LANG_TEMPLATE_INCLUDE_APPNAME' => false,
  'COOKIE_DOMAIN' => '',
  'COOKIE_PATH' => '/',
  'COOKIE_EXPIRE' => 86400,
  'URL_MODEL' => 0,
  'START_ROUTER' => true,
  'URL_PATHINFO_MODEL' => 2,
  'URL_PATHINFO_DEPR' => '/',
  'URL_HTML_SUFFIX' => '.html',
  'DEFAULT_APP' => 'group',
  'DEFAULT_CONTROL' => 'public',
  'DEFAULT_ACTION' => 'index',
  'LOG_RECORD' => false,
  'LOG_FILE_SIZE' => 2097152,
  'LOG_RECORD_LEVEL' => 'EMERG|ALERT|CRIT|ERR',
  'LOG_MUST_RECORD_EXCEPTION' => false,
  'LOG_SQL_ENABLED' => false,
  'SHOW_PAGE_TRACE' => false,
  'SHOW_RUN_TIME' => true,
  'SHOW_DETAIL_TIME' => false,
  'SHOW_USE_MEM' => false,
  'SHOW_DB_TIMES' => true,
  'SHOW_GZIP_STATUS' => false,
  'RUNTIME_CACHE_BACKEND' => 'FileCache',
  'RUNTIME_CACHE_TIME' => 86400,
  'RUNTIME_CACHE_PREFIX' => '~@',
  'RUNTIME_CACHE_TIMES' => 
  array (
    'newuser' => 3600,
    'activeuser' => 3600,
    'hottag' => 3600,
    'hottagtop' => 3600,
    'site' => 3600,
  ),
  'RUNTIME_FILECACHE_PATH' => '',
  'RUNTIME_MEMCACHE_SERVERS' => 
  array (
  ),
  'RUNTIME_MEMCACHE_HOST' => '127.0.0.1',
  'RUNTIME_MEMCACHE_PORT' => 11211,
  'RUNTIME_MEMCACHE_COMPRESSED' => false,
  'RUNTIME_MEMCACHE_PERSISTENT' => true,
  'CACHE_FORCE_NAME' => 'update_cache',
  'ALLOWED_PROBE' => true,
  'UPLOAD_FILE_RULE' => 'time',
  'LANG_ON' => false,
  'LANG_SWITCH' => true,
  'LANG' => 'Zh-cn',
  'URL_DOMAIN_ON' => false,
  'URL_DOMAIN' => '',
  '_ROUTER_' => 
  array (
    'list' => 
    array (
      0 => 'public/index',
      1 => 'page',
    ),
    'space' => 
    array (
      0 => 'space/index',
      1 => 'id',
    ),
    'fresh' => 
    array (
      0 => 'ucenter/view',
      1 => 'id',
    ),
    'help' => 
    array (
      0 => 'homehelp/show',
      1 => 'id',
    ),
    'file' => 
    array (
      0 => 'attachment/show',
      1 => 'id',
    ),
    'site' => 
    array (
      0 => 'homesite/site',
      1 => 'id',
    ),
    'msg' => 
    array (
      0 => 'announcement/show',
      1 => 'id',
    ),
  ),
  'DOMAIN_ON' => false,
  'DOMAIN_TOP' => '',
  'DOMAIN_SUFFIX' => '',
  'U_PRO_VAR' => '',
  'GLOBALS_TAGS' => 
  array (
  ),
  '_CURSCRIPT_' => 
  array (
    0 => 'public::index',
    1 => 'pm',
    2 => 'notice::index',
    3 => 'ucenter,ucenter::index,ucenter::view,ucenter::feed,ucenter::post,ucenter::edit',
    4 => 'attachment::index',
    5 => 'attachment::add,attachment::dialog_add',
    6 => 'attachment::lists',
    7 => 'attachment::attachmentinfo',
    8 => 'attachment::show',
    9 => 'announcement::show',
    10 => 'space::index',
    11 => 'apps::index',
    12 => 'space::index',
    13 => 'online::index',
    14 => 'search::result',
  ),
  'DB_CACHE_FIELDS' => true,
  'DB_CACHE_TIME' => 86400000000,
  'RBAC_ROLE_TABLE' => 'role',
  'RBAC_USERROLE_TABLE' => 'userrole',
  'RBAC_ACCESS_TABLE' => 'access',
  'RBAC_NODE_TABLE' => 'node',
  'USER_AUTH_ON' => true,
  'USER_AUTH_KEY' => 'authid5a0904',
  'ADMIN_USERID' => '1',
  'ADMIN_AUTH_KEY' => 'adminddFf1E',
  'USER_AUTH_MODEL' => 'user',
  'AUTH_PWD_ENCODER' => 'md5',
  'USER_AUTH_GATEWAY' => 'home://public/login',
  'NOT_AUTH_MODULE' => 'public,api,space,misc,wap,apps,search,index,homehelp,homesite',
  'REQUIRE_AUTH_MODULE' => '',
  'NOT_AUTH_ACTION' => '',
  'REQUIRE_AUTH_ACTION' => '',
  'GUEST_AUTH_ON' => true,
  'GUEST_AUTH_ID' => '-1',
  'RBAC_ERROR_PAGE' => 'home://public/rbacerror',
  'RBAC_GUEST_ACCESS' => 
  array (
    'home@stat@*' => true,
    'home@online@*' => true,
    'home@getpassword@*' => true,
    'home@userappeal@*' => true,
    'home@attachmentdownload@*' => true,
    'home@attachmentread@*' => true,
    'home@attachment@*' => true,
    'home@attachment@show' => false,
    'home@attachment@add' => false,
    'home@attachment@normal_upload' => false,
    'home@attachment@add_attachmentcomment' => false,
    'home@homesite@*' => true,
    'home@homehelp@*' => true,
    'home@announcement@*' => true,
    'group@ucenter@*' => true,
    'group@tag@*' => true,
    'group@group@joingroup' => true,
    'group@group@leavegroup' => true,
    'group@group@getcategory' => true,
    'group@grouptopic@set_grouptopicstyle' => true,
    'group@grouptopic@set_grouptopicside' => true,
    'group@create@*' => true,
  ),
  'RBAC_USER_ACCESS' => 
  array (
    'home@spaceadmin@*' => true,
    'home@spaceadmin@transfer' => false,
    'home@spaceadmin@dotransfer' => false,
    'home@pm@*' => true,
    'home@notice@*' => true,
    'home@friend@*' => true,
    'home@ucenter@index' => true,
    'home@ucenter@homefreshtopic' => true,
    'home@ucenter@audit_homefreshcomment' => true,
    'home@ucenter@feed' => true,
    'home@ucenter@tag' => true,
    'home@ucenter@tags' => true,
    'group@groupadmin@*' => true,
    'group@grouptopic@printtable' => true,
    'group@grouptopic@next' => true,
    'group@grouptopic@prev' => true,
    'group@grouptopic@readtopic' => true,
    'group@grouptopic@love' => true,
    'group@grouptopic@love_add' => true,
  ),
  'APP_DEVELOP' => 0,
  'ADMIN_TPL_DIR' => 'Default',
  'FIREBUGFORIE' => false,
  'ADMIN_LANGUAGE_DIR' => 'Zh-cn',
  'CRON_ON' => true,
  'LOGINVIEW_IGNORE' => 
  array (
    0 => 'home@ucenter@view',
    1 => 'group@grouptopic@view',
  ),
  'APP_MENU' => 
  array (
  ),
  'EDITOR_HEIGHT' => 1500,
)
?>