<?php
 /* QeePHP Config File,Do not to modify this file! */ 
 return array (
  'START_GZIP' => true,
  'APP_DEBUG' => false,
  'DB_HOST' => 'localhost',
  'DB_USER' => 'root',
  'DB_PASSWORD' => '',
  'DB_PREFIX' => 'qeephp_',
  'DB_CHAR' => 'utf8',
  'DB_NAME' => '',
  'DB_TYPE' => 'mysql',
  'DB_SCHEMA' => '',
  'DB_PORT' => 3306,
  'DB_CACHE' => false,
  'DB_META_CACHED' => true,
  'DB_DISTRIBUTED' => false,
  'DB_RW_SEPARATE' => false,
  'DB_DSN' => 'mysql://username:password@localhost:3306/dbname',
  'DB_PARAMS' => 
  array (
  ),
  'TEMPLATE_NOT_ALLOWS_FUNC' => 'echo,exit',
  'CACHE_LIFE_TIME' => -1,
  'CACHE_REPLACE_CHILDREN' => false,
  'THEME_SWITCH' => true,
  'TPL_DIR' => 'Default',
  'PHP_OFF' => false,
  'TEMPLATE_TAG_NOTE' => false,
  'TEMPLATE_SUFFIX' => '.html',
  'ERROR_PAGE' => '',
  'SHOW_ERROR_MSG' => true,
  'TMPL_ACTION_ERROR' => 'public+success',
  'TMPL_ACTION_SUCCESS' => 'public+success',
  'TMPL_MODULE_ACTION_DEPR' => '_',
  'DEFAULT_AJAX_RETURN' => 'JSON',
  'TMPL_VAR_IDENTIFY' => 'array',
  'AUTO_ACCEPT_LANGUAGE' => true,
  'QEEPHP_AUTH_KEY' => 'qeephp_auth_key',
  'RBAC_DATA_PREFIX' => 'rbac_data_prefix',
  'TIME_ZONE' => 'Asia/Shanghai',
  'COOKIE_PREFIX' => 'qeephp_',
  'COOKIE_LANG_TEMPLATE_INCLUDE_APPNAME' => false,
  'COOKIE_DOMAIN' => '',
  'COOKIE_PATH' => '/',
  'COOKIE_EXPIRE' => 86400,
  'URL_MODEL' => 0,
  'START_ROUTER' => false,
  'URL_PATHINFO_MODEL' => 2,
  'URL_PATHINFO_DEPR' => '/',
  'URL_HTML_SUFFIX' => '',
  'DEFAULT_APP' => 'home',
  'DEFAULT_CONTROL' => 'public',
  'DEFAULT_ACTION' => 'index',
  'LOG_RECORD' => false,
  'LOG_FILE_SIZE' => 2097152,
  'LOG_RECORD_LEVEL' => 'EMERG|ALERT|CRIT|ERR',
  'LOG_MUST_RECORD_EXCEPTION' => false,
  'LOG_SQL_ENABLED' => false,
  'SHOW_PAGE_TRACE' => false,
  'SHOW_RUN_TIME' => false,
  'SHOW_DETAIL_TIME' => false,
  'SHOW_USE_MEM' => false,
  'SHOW_DB_TIMES' => false,
  'SHOW_GZIP_STATUS' => false,
  'RUNTIME_CACHE_BACKEND' => 'FileCache',
  'CACHE_FORCE_NAME' => 'update_cache',
  'ALLOWED_PROBE' => true,
  'UPLOAD_FILE_RULE' => 'time',
  'LANG_ON' => true,
  'LANG_SWITCH' => true,
  'LANG' => 'zh-cn',
  'URL_DOMAIN_ON' => true,
  'URL_DOMAIN' => '',
  '_ROUTER_' => 
  array (
  ),
  'DOMAIN_ON' => false,
  'DOMAIN_TOP' => '',
  'DOMAIN_SUFFIX' => '',
  'U_PRO_VAR' => 'D',
  'NOT_ALLOWED_EMPTYCONTROL_VIEW' => true,
)
?>